Repository tsoporan/fittrak, pull requests merged in 2018-07, with the labels that each got.

#48 Account templates
  Pipfile
  Pipfile.lock
  README.md
  fittrak/fittrak/schema.py
  fittrak/fittrak/settings.py
  fittrak/fittrak/templates/base.html
  fittrak/fittrak/templates/base_accounts.html
  fittrak/fittrak/templates/index.html
  fittrak/fittrak/templates/registration/login.html
  fittrak/fittrak/templates/registration/registration_form.html
  fittrak/fittrak/urls.py
  fittrak/users/schema.py
Labels: back-end, front-end

#50 Pull workouts on homepage
  .circleci/config.yml
  fittrak-client/package.json
  fittrak-client/src/App.vue
  fittrak-client/src/components/HelloWorld.vue
  fittrak-client/src/components/Nav.vue
  fittrak-client/src/components/WorkoutItem.vue
  fittrak-client/src/components/WorkoutList.vue
  fittrak-client/src/main.js
  fittrak-client/src/views/Home.vue
  fittrak-client/vue.config.js
  fittrak-client/yarn.lock
  fittrak/fittrak/schema.py
  fittrak/fittrak/settings.py
  fittrak/fittrak/templates/base.html
  fittrak/fittrak/templates/index.html
  fittrak/fittrak/urls.py
  fittrak/users/schema.py
  fittrak/workouts/admin.py
  fittrak/workouts/models.py
Labels: back-end, enhancement, front-end

#51 Hookup create workout
  .gitignore
  fittrak-client/.babelrc
  fittrak-client/.eslintrc.js
  fittrak-client/babel.config.js
  fittrak-client/package.json
  fittrak-client/public/img/icons/android-chrome-192x192.png
  fittrak-client/public/img/icons/android-chrome-512x512.png
  fittrak-client/public/img/icons/apple-touch-icon-120x120.png
  fittrak-client/public/img/icons/apple-touch-icon-152x152.png
  fittrak-client/public/img/icons/apple-touch-icon-180x180.png
  fittrak-client/public/img/icons/apple-touch-icon-60x60.png
  fittrak-client/public/img/icons/apple-touch-icon-76x76.png
  fittrak-client/public/img/icons/apple-touch-icon.png
  fittrak-client/public/img/icons/favicon-16x16.png
  fittrak-client/public/img/icons/favicon-32x32.png
  fittrak-client/public/img/icons/msapplication-icon-144x144.png
  fittrak-client/public/img/icons/mstile-150x150.png
  fittrak-client/public/img/icons/safari-pinned-tab.svg
  fittrak-client/public/index.html
  fittrak-client/public/manifest.json
  fittrak-client/src/App.vue
  fittrak-client/src/assets/logo.png
  fittrak-client/src/components/CreateWorkout.vue
  fittrak-client/src/components/History.vue
  fittrak-client/src/components/Home.vue
  fittrak-client/src/components/Nav.vue
  fittrak-client/src/components/Settings.vue
  fittrak-client/src/components/WorkoutDetail.vue
  fittrak-client/src/components/WorkoutList.vue
  fittrak-client/src/graphql/mutations/createWorkout.graphql
  fittrak-client/src/graphql/queries/viewerWorkouts.graphql
  fittrak-client/src/main.js
  fittrak-client/src/registerServiceWorker.js
  fittrak-client/src/router.js
  fittrak-client/src/router/index.js
  fittrak-client/src/store.js
  fittrak-client/src/views/About.vue
  fittrak-client/src/views/Test.vue
  fittrak-client/vue.config.js
  fittrak-client/yarn.lock
Labels: back-end, feature, front-end

#54 Remove workouts
  fittrak-client/src/components/CreateWorkout.vue
  fittrak-client/src/components/WorkoutItem.vue
  fittrak-client/src/components/WorkoutList.vue
  fittrak-client/src/graphql/mutations/removeWorkout.graphql
Labels: front-end

#57 Updated circleci config
  .circleci/config.yml
  fittrak-client/src/components/WorkoutItem.vue
Labels: devops

#55 Add exercises to workout
  fittrak-client/src/components/AddExercise.vue
  fittrak-client/src/components/WorkoutDetail.vue
  fittrak-client/src/components/WorkoutItem.vue
  fittrak-client/src/graphql/mutations/addExercise.graphql
  fittrak-client/src/router/index.js
  fittrak/fittrak/schema.py
  fittrak/workouts/migrations/0003_auto_20180711_1636.py
  fittrak/workouts/migrations/0003_auto_20180711_2121.py
  fittrak/workouts/migrations/0004_auto_20180711_1639.py
  fittrak/workouts/migrations/0005_merge_20180711_2123.py
  fittrak/workouts/models.py
  fittrak/workouts/schema.py
Labels: back-end, front-end, workflow

#59 Exercise list and item view
  fittrak-client/src/components/AddExercise.vue
  fittrak-client/src/components/CreateWorkout.vue
  fittrak-client/src/components/ExerciseItem.vue
  fittrak-client/src/components/ExerciseList.vue
  fittrak-client/src/components/WorkoutDetail.vue
  fittrak-client/src/components/WorkoutItem.vue
  fittrak-client/src/components/WorkoutList.vue
  fittrak-client/src/graphql/mutations/addExercise.graphql
  fittrak-client/src/graphql/queries/workout.graphql
  fittrak-client/src/graphql/queries/workouts.graphql
  fittrak/users/schema.py
  fittrak/workouts/models.py
  fittrak/workouts/schema.py
Labels: back-end, front-end

#64 Test framework setup
  .circleci/config.yml
  Pipfile
  Pipfile.lock
  fittrak-client/.babelrc
  fittrak-client/.eslintrc.js
  fittrak-client/package.json
  fittrak-client/test/App.spec.js
  fittrak-client/test/__snapshots__/App.spec.js.snap
  fittrak-client/yarn.lock
  fittrak/users/tests.py
Labels: back-end, front-end

#67 Add AddSet endpoint
  fittrak-client/vue.config.js
  fittrak/workouts/models.py
  fittrak/workouts/schema.py
Labels: back-end

#72 Added render tests for SetItem and SetList
  fittrak-client/src/__tests__/SetItem.spec.js
  fittrak-client/src/__tests__/SetList.spec.js
  fittrak-client/src/__tests__/__snapshots__/SetItem.spec.js.snap
  fittrak-client/src/__tests__/__snapshots__/SetList.spec.js.snap
Labels: front-end

#73 UpdateWorkout mutation
  fittrak/fittrak/schema.py
  fittrak/workouts/schema.py
Labels: back-end

#74 Finish workout
  fittrak-client/src/components/constants.js
  fittrak-client/src/components/exercises/AddExercise.vue
  fittrak-client/src/components/exercises/ExerciseList.vue
  fittrak-client/src/components/workouts/FinishWorkout.vue
  fittrak-client/src/components/workouts/WorkoutDetail.vue
  fittrak-client/src/components/workouts/WorkoutItem.vue
  fittrak-client/src/graphql/mutations/updateWorkout.graphql
  fittrak-client/src/graphql/queries/workout.graphql
  fittrak/workouts/models.py
  fittrak/workouts/schema.py
Labels: front-end, workflow

#78 Remove exercise
  fittrak-client/src/components/exercises/ExerciseItem.vue
  fittrak-client/src/components/exercises/RemoveExercise.vue
  fittrak-client/src/components/workouts/WorkoutItem.vue
  fittrak-client/src/graphql/mutations/removeExercise.graphql
  fittrak-client/src/graphql/queries/workout.graphql
  fittrak-client/src/graphql/queries/workouts.graphql
  fittrak/fittrak/schema.py
  fittrak/workouts/graphql/exercises.py
Labels: back-end, front-end

#79 Remove set
  fittrak-client/src/__tests__/__snapshots__/SetItem.spec.js.snap
  fittrak-client/src/components/sets/RemoveSet.vue
  fittrak-client/src/components/sets/SetItem.vue
  fittrak-client/src/graphql/mutations/removeSet.graphql
  fittrak/fittrak/schema.py
  fittrak/workouts/graphql/sets.py
Labels: back-end, front-end

#83 Set up Bulma
  fittrak-client/__mocks__/styleMock.js
  fittrak-client/package.json
  fittrak-client/src/App.vue
  fittrak-client/yarn.lock
  fittrak/fittrak/templates/base.html
  fittrak/fittrak/templates/base_accounts.html
  fittrak/fittrak/templates/index.html
  fittrak/fittrak/templates/registration/login.html
  fittrak/fittrak/templates/registration/registration_form.html
Labels: back-end, front-end

#84 Start workout
  fittrak-client/src/components/constants.js
  fittrak-client/src/components/workouts/StartWorkout.vue
  fittrak-client/src/components/workouts/WorkoutDetail.vue
  fittrak-client/src/graphql/mutations/updateWorkout.graphql
  fittrak/workouts/graphql/workouts.py
  fittrak/workouts/models.py
Labels: back-end, front-end

#85 Styling for account forms
  fittrak/fittrak/templates/base.html
  fittrak/fittrak/templates/base_accounts.html
  fittrak/fittrak/templates/registration/login.html
  fittrak/fittrak/templates/registration/registration_form.html
Labels: front-end

#86 81 basic styling
  fittrak-client/src/App.vue
  fittrak-client/src/__tests__/__snapshots__/App.spec.js.snap
  fittrak-client/src/components/Navigation.vue
  fittrak-client/src/components/workouts/CreateWorkout.vue
  fittrak-client/src/components/workouts/WorkoutDetail.vue
  fittrak-client/src/components/workouts/WorkoutList.vue
  fittrak-client/src/graphql/queries/viewer.graphql
  fittrak-client/src/graphql/queries/workout.graphql
  fittrak-client/src/graphql/queries/workouts.graphql
  fittrak/fittrak/templates/base.html
  fittrak/fittrak/templates/index.html
  fittrak/users/schema.py
  fittrak/workouts/graphql/schema.py
Labels: back-end, front-end

#87 81 basic styling
  fittrak-client/src/App.vue
  fittrak-client/src/__tests__/__snapshots__/AddSet.spec.js.snap
  fittrak-client/src/__tests__/__snapshots__/App.spec.js.snap
  fittrak-client/src/__tests__/__snapshots__/SetItem.spec.js.snap
  fittrak-client/src/__tests__/__snapshots__/SetList.spec.js.snap
  fittrak-client/src/components/exercises/AddExercise.vue
  fittrak-client/src/components/exercises/ExerciseItem.vue
  fittrak-client/src/components/exercises/RemoveExercise.vue
  fittrak-client/src/components/pages/History.vue
  fittrak-client/src/components/pages/Home.vue
  fittrak-client/src/components/pages/Settings.vue
  fittrak-client/src/components/sets/AddSet.vue
  fittrak-client/src/components/sets/RemoveSet.vue
  fittrak-client/src/components/sets/SetItem.vue
  fittrak-client/src/components/sets/SetList.vue
  fittrak-client/src/components/workouts/CreateWorkout.vue
  fittrak-client/src/components/workouts/FinishWorkout.vue
  fittrak-client/src/components/workouts/StartWorkout.vue
  fittrak-client/src/components/workouts/WorkoutDetail.vue
  fittrak-client/src/components/workouts/WorkoutItem.vue
  fittrak-client/src/components/workouts/WorkoutList.vue
Labels: enhancement, front-end

#89 Dockerize
  .circleci/config.yml
  .dockerignore
  Dockerfile
  Pipfile
  Pipfile.lock
  fittrak/fittrak/settings.py
  start.sh
Labels: back-end, devops

#90 Initial k8s deployment
  .gitignore
  conf/default.conf
  conf/nginx.conf
  docker/Dockerfile.app
  docker/Dockerfile.static
  fittrak-client/src/main.js
  fittrak/fittrak/templates/base.html
  infra/k8s/deployment.yaml
  infra/k8s/ingress.yaml
  infra/k8s/secrets.yaml
  infra/k8s/service.yaml
Labels: devops
